### PR TITLE
Fixed coding style issues and adding input checks to functions

### LINKED ISSUE #33: improve coding style
According to the [B-Cubed guidelines](https://docs.b-cubed.eu/dev-guide/#r-style) (= [tidyverse style guide](https://style.tidyverse.org/))
Both in the Readme and functions.

### PR DESCRIPTION
**Pull request by LBreugelmans**
- [x] make output of generate_pd_map_and_indicator() silent in readme to avoid showing personal folder path
- [x] fix #33 
- [x] add input checks to start of functions
- [x] update version
- [x] run codemeta
- [x] assign reviewer

### CODE REVIEW

File: R/calculate_FaithPD.R [hunk 1]
```diff
@@ -7,22 +7,47 @@
 #' format that was parsed by `ape::read_tree()`
 #' @param species A character vector where each element is a species, and more
 #' specifically, matches a tip label of the phylogenetic tree exactly
-#' @param MRCA Node id of the taxon that represents the most recent common
-#' ancestor of the set of species under study
+#' @param mrca_node_id Node id of the taxon that represents the most recent common
```
Comment (wlangera) [inline R/calculate_FaithPD.R:10]: lines should not be more than 80 characters, this line is 82

File: R/calculate_FaithPD.R [hunk 2]
```diff
@@ -62,17 +87,7 @@ calculate_faithpd <- function(tree, species, MRCA) {
...
-# unrooted) trees to make sure methodology is sound
-
-# calculate_pd_easy <- function(tree, species){
-#  y<-which.edge(rtree, trio)
-#  edge_lengths <- tree$edge.length[y]
-#  pd <- sum(edge_lengths)
-#  return(pd)
-#  print(paste("Phylogenetic diversity:", pd))
-# }
+
```
Comment (wlangera) [inline R/calculate_FaithPD.R:93]: Trailing blank lines are superfluous (2 witregels op einde van R script mogen weg)

File: R/generate_map_and_indicator.R [hunk 3]
```diff
@@ -184,17 +223,16 @@ generate_map_and_indicator <- function(
...
       n_total <- nrow(centroids)
-      PD_indicator <- (n_intersecting / n_total) * 100
-      indicators[["Overall"]] <- PD_indicator
+      pd_indicator <- (n_intersecting / n_total) * 100
+      indicators[["Overall"]] <- pd_indicator
 
       print(paste("The percentage of high PD grid cells that fall within",
-                  "protected areas is", PD_indicator, "%"))
-
+                  "protected areas is", round(indicators$Overall, digits=2), "%"))
```
Comment (wlangera) [inline R/generate_map_and_indicator.R:230]:
```suggestion
                  "protected areas is", round(indicators$Overall, digits = 2), "%"))
```

Comment (wlangera) [reply R/generate_map_and_indicator.R:230]: Lines should not be more than 80 characters

File: R/get_pd_cube.R [hunk 4]
```diff
@@ -17,26 +17,51 @@
...
+  if (!is.null(timegroup)) {
+    if (!is.numeric(timegroup) || timegroup <= 0 || length(timegroup) != 1 ||
+        timegroup != as.integer(timegroup)) {
+      stop("Error: 'timegroup' must be a single positive integer or NULL.")
+    }
+  }
+
+  # Check that selected metric(s) are correctly specified
+  available_metrics <- list("faith")
+  if (!metric %in% available_metrics){stop("The selected PD metric is not available.")}
```
Comment (wlangera) [inline R/get_pd_cube.R:45]:
```suggestion
stopifnot("The selected PD metric is not available." = metric %in% available_metrics)
```

File: R/get_pd_cube.R [hunk 5]
```diff
@@ -17,26 +17,51 @@
...
+  mrca_node_id <- ape::getMRCA(tree, all_matched_sp)
 
   # Calculate PD metric
   if (metric == "faith") {
-    PD_cube <- aggr_cube %>%
-      mutate(PD = unlist(purrr::map(aggr_cube$orig_tiplabels,
-                                    ~ calculate_faithpd(tree, unlist(.x), MRCA))
+    pd_cube <- aggr_cube %>%
+      mutate(pd = unlist(purrr::map(aggr_cube$orig_tiplabels,
+                                    ~ calculate_faithpd(tree, unlist(.x), mrca_node_id))
```
Comment (wlangera) [inline R/get_pd_cube.R:61]: lines should not be more than 80 characters

File: R/retrieve_example_data.R [hunk 6]
```diff
@@ -25,78 +25,50 @@
...
+  loaders <- list(
+    tree = function(path) {
+      tree <- ape::read.tree(path)
+      tree$tip.label <- gsub("_", " ", tree$tip.label)
+      tree
+    },
+    cube = function(path) utils::read.csv(path, stringsAsFactors = FALSE, sep = "\t"),
+    grid = sf::st_read,
+    pa = sf::st_read,
+    matched_nona = function(path) read.csv(path, stringsAsFactors = FALSE, sep = ",")
```
Comment (wlangera) [inline R/retrieve_example_data.R:59]: lines should not be more than 80 characters

File: R/retrieve_example_data.R [hunk 7]
```diff
@@ -25,78 +25,50 @@
...
-            )
-          )
+  # Define loader functions for each data type
+  loaders <- list(
+    tree = function(path) {
+      tree <- ape::read.tree(path)
+      tree$tip.label <- gsub("_", " ", tree$tip.label)
+      tree
+    },
+    cube = function(path) utils::read.csv(path, stringsAsFactors = FALSE, sep = "\t"),
```
Comment (wlangera) [inline R/retrieve_example_data.R:56]: lines should not be more than 80 characters

**Review by wlangera — CHANGES_REQUESTED** [review]
Hi

Thanks for the fast work.
There are some small comments, often because you have more than 80 characters on one line.

It is not really good practice to have all these if statements, this increases the [cyclomatic complexity](https://www.geeksforgeeks.org/cyclomatic-complexity/). There is a  `stopifnot()` function and the assertthat package also has some good functions. In[ the guidelines](https://www.geeksforgeeks.org/cyclomatic-complexity/) they have other recommendations.
I will make a branch with an example. Your choice if you implement this.

I have updated the package version in the zenodo file

File: R/aggregate_cube.R [hunk 8]
```diff
@@ -22,6 +22,41 @@
 
 aggregate_cube <- function(mcube, timegroup = NULL) {
 
+  # Check that mcube is a dataframe or tibble
+  if (!is.data.frame(mcube)) {
```
Comment (wlangera) [inline R/aggregate_cube.R:26]: stopifnot("Error: 'mcube' must be a dataframe or tibble." =
              inherits(mcube, "data.frame"))

File: R/generate_map_and_indicator.R [hunk 9]
```diff
@@ -36,22 +35,62 @@
...
+  if (missing(grid) || !inherits(grid, "sf")) {
+    stop("`grid` must be provided and should be an `sf` object.")
+  }
+
+  if (!all(sf::st_is_valid(grid))) {
+    stop("Some geometries in `grid` are invalid. Please fix them before
+         proceeding.")
+  }
+
+  if (!"CELLCODE" %in% colnames(grid)) {
```
Comment (wlangera) [inline R/generate_map_and_indicator.R:63]: stopifnot (and assertthat):

stopifnot("`grid` must contain a column named 'CELLCODE' for grid cell codes." = assertthat::has_name(grid, "CELLCODE"))

**Comment by wlangera** [comment]
Please run `devtools::document()` and `codemetar::write_codemeta()` after your changes

File: R/generate_map_and_indicator.R (hunk 9 above)
Comment (LBreugelmans) [reply R/generate_map_and_indicator.R:63]: Doublecheck other functions for similar use

**Review by wlangera — COMMENTED** [review]
Hi, please have a look at my final PR [here](https://github.com/b-cubed-eu/pdindicatoR/pull/49).

I fixed some  minor coding style things, and a file name to lower letters.
I also bumped the version to 0.1.0 because the whole pull request is rather large.
No big changes.

If you agree with that PR, we can merge with main :)

**Review by wlangera — APPROVED** [review]
